### ISSUE TITLE
On mobile profile picture and text overlap

### ISSUE THREAD

**Issue by johnmosesman** [HolyArchers/holyarchers#13]
![image](https://cloud.githubusercontent.com/assets/3760568/5572922/95323a46-8f6a-11e4-8711-7f2236b8caf7.png)

**Comment by ryanlabouve** [comment]
This is unfortunately a WP issue.

What I'm doing you can see on the 3rd line: `col-xs-12 and col-sm-4`... that basically blows my picture out to full-width  when it gets on mobile.

There's probably a better solution for this long term, but for the shot I'd recommend just fixing it in the CMS.

```language-html
<div class="row">
    <div class="col-xs-12 col-sm-4">
    <div class="profile-pic profile-john"></div>
</div>

<div class="col-xs-8">
    <h1>John Mosesman</h1>
    <h2>Full Stack Developer</h2>
    <p>John is a web developer for <a href="http://www.lifechurch.tv/">LifeChurch.tv</a>. He doesn't like to pay for things, is actively trying to become a coffee snob, and has an above average squat form.
    </p>
</div>
```
