### ISSUE TITLE
This section is choppy for me visually

### ISSUE THREAD

**Issue by johnmosesman** [HolyArchers/holyarchers#19]
### Create Action

Since we're changing our application's state (persisting a new model), let's handle our new action in the `lists` route. Below is the file in its entirety. Notice that action functions go inside a special property hash called `actions`:

```language-javascript
// routes/lists.js
export default Ember.Route.extend({
  model: function() {
    return this.store.find('list');
  },

  actions: {
    createList: function() {
      var newListTitle = this.controllerFor('lists').get('newListTitle');

      if (Ember.isBlank(newListTitle)) { return false; }

    // 1
      var list = this.store.createRecord('list', {
        title: newListTitle
      });

    // 2
      this.controllerFor('lists').set('newListTitle', '');

      var _this = this;   // Save the current context since below it is out of scope.
      
      // 3
      list.save().then(function(list) {
        _this.transitionTo('lists.show', list);   // 4
      });
    }
  }
});
```
  
In our `createList` function the first thing we do is retrieve the `<input>`'s value by accessing the property we defined in the `{{input}}` helper\*. Next, we check if the `newListTitle` variable is blank using the Ember helper [isBlank](http://emberjs.com/api/#method_isBlank), and if it is we return `false` to leave the function\*\* .

If we do have a title, we do the following:

1. Call `createRecord` with the new title to add a new `List` object to the store
2. Reset the `<input>`'s value back to blank
3. Call `save()` on the new model
4. And once the call to `save()` completes, we call a router function, `transitionTo`, to show the new list.

There's a decent amount of stuff happening in this function, so here are some key points:

- `createRecord()` adds the object to the store, but doesn't persist the object
- `save()` actually does the persistence
- We're calling `transitionTo` after the object saves by tieing into a promise (using the `then` function). More on promises [here](http://emberjs.com/api/classes/RSVP.Promise.html).

If you're not totally sure what's going on here it might be useful to take some time to research these functions.

 \* I'm not totally happy with how we pull back the controller here to access our input property, but I'd rather stick to keeping state altering functions in the router rather than putting this function in a controller.
 
 ** Returning `false` also stops the event from propogating up the chain——more on this later.

**Comment by ryanlabouve** [comment]
I think this is part a larger issue. Asked Seth for some direction:

> 
all of your type is the same size
for instance this page
http://www.smashingmagazine.com/2014/12/10/mastering-fireworks-css-properties-panel-css-professionalzr/
has a lot of variation in type sizes

So, I think that I've got some work to do. lol

**Comment by ryanlabouve** [comment]
I did some work on this. Honestly I could do a ton more. I'm closing for now and we'll reopen later.
